package models;

public enum EntreeType {
	BREAKFAST, LUNCH, DINNER, SNAKE, DESERT, VEGAN, VEGETARIAN, GLUTEN_FREE, CHICKEN, BEEF, SEAFOOD, PALEO, LOW_CARBS, ATKINS, SPANISH, MEXICAN, ITALIAN, ASIAN, THAI, KOSHER;

}
